### ISSUE TITLE
Show legacy record data in A&R front end

### ISSUE THREAD

**Issue by kgorana** [bcgov/bcparks-ar-admin#269]
## Description

Based on [BRS-816: Migrate historical data into A&R system](https://bcparksdigital.atlassian.net/browse/BRS-816)
, all legacy parks/subareas and most records should already be visible in the system. This change is to ensure that the new `Legacy Data` activity and any other historical activities are visible to the FE.

As a user, I want to be able to see legacy records for all subareas activities, even if that subarea doesn’t have that activity in its current config (ie - subarea used to have `Day Use`, but then `Day Use` was removed from the subarea, despite there still being `Day Use` records in the system). The current system only fetches activity records if the subarea is currently configured to have that activity.

In some cases with historical data, and particularly with the Legacy Data activity, the current system will not fetch these records.

## Acceptance Criteria:

`Legacy Data` and other legacy activity records are surfaced when that particular date/park/subarea combination is queried.

## Linked issues
blocks

- [ ] [BRS-820](https://bcparksdigital.atlassian.net/browse/BRS-820)

created by

- [x] [BRS-680](https://bcparksdigital.atlassian.net/browse/BRS-680)

is blocked by

- [ ] [BRS-816](https://bcparksdigital.atlassian.net/browse/BRS-816)
- [x] [BRS-971](https://bcparksdigital.atlassian.net/browse/BRS-971)

is cloned by

- [x] [BRS-972](https://bcparksdigital.atlassian.net/browse/BRS-972)

**Comment by LindsayMacfarlane** [comment]
October 11, 2024 prioritization session: A&R team identified this ticket/issue as high priority. 

Mural board: https://app.mural.co/t/bcparks2575/m/bcparks2575/1728427370222/4c9714df914c7ec8bdcf20a9ee1999cc9e664a27?wid=0-1728427872927

**Comment by Dianadec** [comment]
Connected to #348  but not a duplicate
